{
 "title": "Audit machine",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU LOAD AGENT A",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * load_load1{instance=\"http://agent_a:9101/audit.json\"} / 8",
     "legendFormat": "CPU Load 1 min "
    },
    {
     "expr": "100 * load_load5{instance=\"http://agent_a:9101/audit.json\"} / 8",
     "legendFormat": "CPU Load 5 min"
    },
    {
     "expr": "100 * load_load15{instance=\"http://agent_a:9101/audit.json\"} / 8",
     "legendFormat": "CPU Load 15 min"
    }
   ]
  },
  {
   "title": "CPU USAGE ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{instance=\"http://agent_a:9101/audit.json\"}",
     "legendFormat": "Cpu agent A"
    },
    {
     "expr": "cpu_usage_percent{instance=\"http://agent_b:9102/audit.json\"}",
     "legendFormat": "Cpu agent B"
    }
   ]
  },
  {
   "title": "CPU LOAD AGENT B",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * load_load1{instance=\"http://agent_b:9102/audit.json\"} / 8",
     "legendFormat": "CPU Load 1 min "
    },
    {
     "expr": "100 * load_load5{instance=\"http://agent_b:9102/audit.json\"} / 8",
     "legendFormat": "CPU Load 5 min"
    },
    {
     "expr": "100 * load_load15{instance=\"http://agent_b:9102/audit.json\"} / 8",
     "legendFormat": "CPU Load 15 min"
    }
   ]
  },
  {
   "title": "RAM USAGE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * mem_used_bytes{instance=\"http://agent_a:9101/audit.json\"}/ mem_total_bytes{instance=\"http://agent_a:9101/audit.json\"}\n",
     "legendFormat": "RAM Agent A"
    },
    {
     "expr": "100 * mem_used_bytes{instance=\"http://agent_b:9102/audit.json\"}/ mem_total_bytes{instance=\"http://agent_b:9102/audit.json\"}",
     "legendFormat": "RAM Agent B"
    }
   ]
  },
  {
   "title": "DISK USAGE AGENT A",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * disk_used_bytes{instance=\"http://agent_a:9101/audit.json\"}\n  / disk_total_bytes{instance=\"http://agent_a:9101/audit.json\"}\n",
     "legendFormat": "{{device}} : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "DISK USAGE AGENT B",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * disk_used_bytes{instance=\"http://agent_b:9102/audit.json\"}\n  / disk_total_bytes{instance=\"http://agent_b:9102/audit.json\"}\n",
     "legendFormat": "{{device}} : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Service status Agent A",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "service_up{instance=\"http://agent_a:9101/audit.json\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service status Agent B",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "service_up{instance=\"http://agent_b:9102/audit.json\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}