{
 "title": "Audit machine",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "New panel",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_bytes{mountpoint=\"/\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "disk_used_bytes{mountpoint=\"/home\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "disk_used_bytes{mountpoint=\"/efi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM USAGE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * mem_used_bytes{instance=\"http://agent_a:9101/audit.json\"}/ mem_total_bytes{instance=\"http://agent_a:9101/audit.json\"}\n",
     "legendFormat": "RAM Agent A"
    },
    {
     "expr": "100 * mem_used_bytes{instance=\"http://agent_b:9102/audit.json\"}/ mem_total_bytes{instance=\"http://agent_b:9102/audit.json\"}",
     "legendFormat": "RAM Agent B"
    }
   ]
  },
  {
   "title": "CPU USAGE ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{instance=\"http://agent_a:9101/audit.json\"}",
     "legendFormat": "Cpu agent A"
    },
    {
     "expr": "cpu_usage_percent{instance=\"http://agent_b:9102/audit.json\"}",
     "legendFormat": "Cpu agent B"
    }
   ]
  },
  {
   "title": "Load Average ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rotghz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_load1{instance=\"http://agent_a:9101/audit.json\"}",
     "legendFormat": "CPU LOAD 1 (Agent A)"
    },
    {
     "expr": "cpu_load5{instance=\"http://agent_a:9101/audit.json\"}",
     "legendFormat": "CPU LOAD 5 (Agent A)"
    },
    {
     "expr": "cpu_load15{instance=\"http://agent_a:9101/audit.json\"}",
     "legendFormat": "CPU LOAD 15 (Agent A)"
    },
    {
     "expr": "cpu_load1{instance=\"http://agent_b:9102/audit.json\"}",
     "legendFormat": "CPU LOAD 1 (Agent B)"
    },
    {
     "expr": "cpu_load5{instance=\"http://agent_b:9102/audit.json\"}",
     "legendFormat": "CPU LOAD 5 (Agent B)"
    },
    {
     "expr": "cpu_load15{instance=\"http://agent_b:9102/audit.json\"}",
     "legendFormat": "CPU LOAD 15 (Agent B)"
    }
   ]
  }
 ]
}